/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as StudyRouteImport } from './routes/study'
import { Route as ProductivityRouteImport } from './routes/productivity'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductivityRoute = ProductivityRouteImport.update({
  id: '/productivity',
  path: '/productivity',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/ai-tools': typeof AiToolsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/career': typeof CareerRoute
  '/finance': typeof FinanceRoute
  '/goals': typeof GoalsRoute
  '/international': typeof InternationalRoute
  '/mentor': typeof MentorRoute
  '/notes': typeof NotesRoute
  '/productivity': typeof ProductivityRoute
  '/study': typeof StudyRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/ai-tools': typeof AiToolsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/career': typeof CareerRoute
  '/finance': typeof FinanceRoute
  '/goals': typeof GoalsRoute
  '/international': typeof InternationalRoute
  '/mentor': typeof MentorRoute
  '/notes': typeof NotesRoute
  '/productivity': typeof ProductivityRoute
  '/study': typeof StudyRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/ai-tools': typeof AiToolsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/career': typeof CareerRoute
  '/finance': typeof FinanceRoute
  '/goals': typeof GoalsRoute
  '/international': typeof InternationalRoute
  '/mentor': typeof MentorRoute
  '/notes': typeof NotesRoute
  '/productivity': typeof ProductivityRoute
  '/study': typeof StudyRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academics'
    | '/ai-tools'
    | '/analytics'
    | '/auth'
    | '/career'
    | '/finance'
    | '/goals'
    | '/international'
    | '/mentor'
    | '/notes'
    | '/productivity'
    | '/study'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academics'
    | '/ai-tools'
    | '/analytics'
    | '/auth'
    | '/career'
    | '/finance'
    | '/goals'
    | '/international'
    | '/mentor'
    | '/notes'
    | '/productivity'
    | '/study'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/academics'
    | '/ai-tools'
    | '/analytics'
    | '/auth'
    | '/career'
    | '/finance'
    | '/goals'
    | '/international'
    | '/mentor'
    | '/notes'
    | '/productivity'
    | '/study'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicsRoute: typeof AcademicsRoute
  AiToolsRoute: typeof AiToolsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  CareerRoute: typeof CareerRoute
  FinanceRoute: typeof FinanceRoute
  GoalsRoute: typeof GoalsRoute
  InternationalRoute: typeof InternationalRoute
  MentorRoute: typeof MentorRoute
  NotesRoute: typeof NotesRoute
  ProductivityRoute: typeof ProductivityRoute
  StudyRoute: typeof StudyRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productivity': {
      id: '/productivity'
      path: '/productivity'
      fullPath: '/productivity'
      preLoaderRoute: typeof ProductivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicsRoute: AcademicsRoute,
  AiToolsRoute: AiToolsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  CareerRoute: CareerRoute,
  FinanceRoute: FinanceRoute,
  GoalsRoute: GoalsRoute,
  InternationalRoute: InternationalRoute,
  MentorRoute: MentorRoute,
  NotesRoute: NotesRoute,
  ProductivityRoute: ProductivityRoute,
  StudyRoute: StudyRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
